### ISSUE TITLE
Zookeeper is not updated

### ISSUE THREAD

**Issue by javieryanez** [bitnami/bitnami-docker-zookeeper#10]
Currently the generated image contains Zookeeper version 3.4.12. The latest version is 3.4.13. It is especially important to upgrade to 3.4.13 for the fix of the issue [ZOOKEEPER-2184](https://issues.apache.org/jira/browse/ZOOKEEPER-2184) that affects Docker operation.

**Comment by tompizmor** [comment]
Hello @javieryanez,

Thanks for reporting it! We have detected an issue in our version tracking system affecting zookeeper so we missed that version. We already fixed so the latest version of Zookeeper should be released soon.

**Comment by tompizmor** [comment]
@javieryanez, just a quick note to let you know that ZooKeeper 3.4.13 is already released!

**Comment by javieryanez** [comment]
Yes, it's released, pulled and tested. Good job!
