### ISSUE TITLE
Packet len* is out of range

### ISSUE THREAD

**Issue by diman82** [bitnami/bitnami-docker-zookeeper#14]
**Description**

**Steps to reproduce the issue:**

1. Run kubernetes/opnshift deployment
2. View kafka logs
3. Find the related excaption

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by miguelaeh** [comment]
Hi @diman82 ,
Could you provide more information about how did you deploy it, and what is happening please?

**Comment by diman82** [comment]
@miguelaeh Of course.
I'm deploying a Kafka single broker cluster, and using zookeeper for this cause.
kafka-cluster template is the following:

`kind: Template
apiVersion: v1
metadata:
name: kafka-cluster
annotations:
description: "Description"
iconClass: "icon-closure"
tags: "kafka-cluster"
objects:
- kind: DeploymentConfig
apiVersion: v1
metadata:
labels:
app: kafka-cluster
name: kafka-cluster
namespace: icg-msst-onepx-172717
spec:
replicas: 1
selector:
app: kafka-cluster
strategy:
type: Rolling
template:
metadata:
labels:
app: kafka-cluster
citi.app-name: onepx
citi.csi-id: "172717"
citi.installed-product-versions: "1.0.0"
citi.installed-ctc-version-ids: "123456"
citi.app-base-image-product: "kafka-cluster"
citi.app-log-format: "json"
spec:
containers:
- name: kafka
env:
- name: STDOUTLOG
value: '0'
- name: ALLOW_PLAINTEXT_LISTENER
value: "yes"
- name: KAFKA_CFG_ZOOKEEPER_CONNECT
value: 'zookeeper-route-myproject.domain.net:80'
image: >-
docker-icg-dev-local.artifactrepository.domain.net/myproject/kafka:latest
imagePullPolicy: IfNotPresent
ports:
- containerPort: 9092
protocol: TCP
resources:
limits:
cpu: '1'
memory: 7000Mi
requests:
cpu: '1'
memory: 4Gi
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File
- name: zookeeper
env:
- name: STDOUTLOG
value: '0'
- name: ALLOW_ANONYMOUS_LOGIN
value: yes
image: >-
docker-icg-dev-local.artifactrepository.domain.net/myproject/zookeeper:latest
imagePullPolicy: IfNotPresent
ports:
- containerPort: 2181
protocol: TCP
resources:
limits:
cpu: '1'
memory: 7000Mi
requests:
cpu: '1'
memory: 4Gi
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File
imagePullSecrets:
- name: docker-icg-dev
dnsPolicy: ClusterFirst
restartPolicy: Always
terminationGracePeriodSeconds: 60
- kind: Service
apiVersion: v1
metadata:
labels:
io.kompose.service: kafka
name: kafka
spec:
ports:
- name: "9092"
port: 9092
targetPort: 9092
selector:
app: kafka
status:
loadBalancer: {}
- kind: Service
apiVersion: v1
metadata:
labels:
io.kompose.service: zookeeper
name: zookeeper
spec:
ports:
- name: "2181"
port: 2181
targetPort: 2181
selector:
app: zookeeper
status:
loadBalancer: {}
- kind: Route
apiVersion: v1
metadata:
name: kafka-route
annotations:
haproxy.router.openshift.io/timeout: 2400000ms
spec:
ports:
- name: 9092-tcp
port: 9092
protocol: TCP
targetPort: 9092
to:
kind: Service
name: kafka
- kind: Route
apiVersion: v1
metadata:
name: zookeeper-route
annotations:
haproxy.router.openshift.io/timeout: 2400000ms
spec:
ports:
- name: 2181-tcp
port: 2181
protocol: TCP
targetPort: 2181
to:
kind: Service
name: zookeeper
parameters:
- name: IMAGE
displayName: Source Repository URL
description: The image to deploy.
required: true
`
Kafka container log is the following:

> 

Welcome to the Bitnami kafka container
--
  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
  | Send us your feedback at containers@bitnami.com
  |  
  | INFO ==> ** Starting Kafka setup **
  | WARN ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
  | INFO ==> Initializing Kafka...
  | INFO ==> No injected configuration files found, creating default config files
  | INFO ==> ** Kafka setup finished! **
  |  
  | INFO ==> ** Starting Kafka **
  | [2019-08-26 10:36:25,424] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
  | [2019-08-26 10:36:25,915] INFO Registered signal handlers for TERM, INT, HUP (org.apache.kafka.common.utils.LoggingSignalHandler)
  | [2019-08-26 10:36:25,915] INFO starting (kafka.server.KafkaServer)
  | [2019-08-26 10:36:25,916] INFO Connecting to zookeeper on zookeeper-route-icg-msst-onepx-172717.namicggtd10d.nam.nsroot.net:80 (kafka.server.KafkaServer)
  | [2019-08-26 10:36:25,931] INFO [ZooKeeperClient Kafka server] Initializing a new session to zookeeper-route-icg-msst-onepx-172717.namicggtd10d.nam.nsroot.net:80. (kafka.zookeeper.ZooKeeperClient)
  | [2019-08-26 10:36:25,935] INFO Client environment:zookeeper.version=3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf, built on 03/06/2019 16:18 GMT (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,935] INFO Client environment:host.name=kafka-cluster-9-z7jnk (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,935] INFO Client environment:java.version=1.8.0_222 (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,935] INFO Client environment:java.vendor=AdoptOpenJDK (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,935] INFO Client environment:java.home=/opt/bitnami/java (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,935] INFO Client environment:java.class.path=/opt/bitnami/kafka/bin/../libs/activation-1.1.1.jar:/opt/bitnami/kafka/bin/../libs/aopalliance-repackaged-2.5.0.jar:/opt/bitnami/kafka/bin/../libs/argparse4j-0.7.0.jar:/opt/bitnami/kafka/bin/../libs/audience-annotations-0.5.0.jar:/opt/bitnami/kafka/bin/../libs/commons-lang3-3.8.1.jar:/opt/bitnami/kafka/bin/../libs/connect-api-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/connect-basic-auth-extension-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/connect-file-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/connect-json-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/connect-runtime-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/connect-transforms-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/guava-20.0.jar:/opt/bitnami/kafka/bin/../libs/hk2-api-2.5.0.jar:/opt/bitnami/kafka/bin/../libs/hk2-locator-2.5.0.jar:/opt/bitnami/kafka/bin/../libs/hk2-utils-2.5.0.jar:/opt/bitnami/kafka/bin/../libs/jackson-annotations-2.9.9.jar:/opt/bitnami/kafka/bin/../libs/jackson-core-2.9.9.jar:/opt/bitnami/kafka/bin/../libs/jackson-databind-2.9.9.jar:/opt/bitnami/kafka/bin/../libs/jackson-dataformat-csv-2.9.9.jar:/opt/bitnami/kafka/bin/../libs/jackson-datatype-jdk8-2.9.9.jar:/opt/bitnami/kafka/bin/../libs/jackson-jaxrs-base-2.9.9.jar:/opt/bitnami/kafka/bin/../libs/jackson-jaxrs-json-provider-2.9.9.jar:/opt/bitnami/kafka/bin/../libs/jackson-module-jaxb-annotations-2.9.9.jar:/opt/bitnami/kafka/bin/../libs/jackson-module-paranamer-2.9.9.jar:/opt/bitnami/kafka/bin/../libs/jackson-module-scala_2.11-2.9.9.jar:/opt/bitnami/kafka/bin/../libs/jakarta.annotation-api-1.3.4.jar:/opt/bitnami/kafka/bin/../libs/jakarta.inject-2.5.0.jar:/opt/bitnami/kafka/bin/../libs/jakarta.ws.rs-api-2.1.5.jar:/opt/bitnami/kafka/bin/../libs/javassist-3.22.0-CR2.jar:/opt/bitnami/kafka/bin/../libs/javax.servlet-api-3.1.0.jar:/opt/bitnami/kafka/bin/../libs/javax.ws.rs-api-2.1.1.jar:/opt/bitnami/kafka/bin/../libs/jaxb-api-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/jersey-client-2.28.jar:/opt/bitnami/kafka/bin/../libs/jersey-common-2.28.jar:/opt/bitnami/kafka/bin/../libs/jersey-container-servlet-2.28.jar:/opt/bitnami/kafka/bin/../libs/jersey-container-servlet-core-2.28.jar:/opt/bitnami/kafka/bin/../libs/jersey-hk2-2.28.jar:/opt/bitnami/kafka/bin/../libs/jersey-media-jaxb-2.28.jar:/opt/bitnami/kafka/bin/../libs/jersey-server-2.28.jar:/opt/bitnami/kafka/bin/../libs/jetty-client-9.4.18.v20190429.jar:/opt/bitnami/kafka/bin/../libs/jetty-continuation-9.4.18.v20190429.jar:/opt/bitnami/kafka/bin/../libs/jetty-http-9.4.18.v20190429.jar:/opt/bitnami/kafka/bin/../libs/jetty-io-9.4.18.v20190429.jar:/opt/bitnami/kafka/bin/../libs/jetty-security-9.4.18.v20190429.jar:/opt/bitnami/kafka/bin/../libs/jetty-server-9.4.18.v20190429.jar:/opt/bitnami/kafka/bin/../libs/jetty-servlet-9.4.18.v20190429.jar:/opt/bitnami/kafka/bin/../libs/jetty-servlets-9.4.18.v20190429.jar:/opt/bitnami/kafka/bin/../libs/jetty-util-9.4.18.v20190429.jar:/opt/bitnami/kafka/bin/../libs/jopt-simple-5.0.4.jar:/opt/bitnami/kafka/bin/../libs/jsr305-3.0.2.jar:/opt/bitnami/kafka/bin/../libs/kafka-clients-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/kafka-log4j-appender-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/kafka-streams-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/kafka-streams-examples-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/kafka-streams-scala_2.11-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/kafka-streams-test-utils-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/kafka-tools-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/kafka_2.11-2.3.0-sources.jar:/opt/bitnami/kafka/bin/../libs/kafka_2.11-2.3.0.jar:/opt/bitnami/kafka/bin/../libs/log4j-1.2.17.jar:/opt/bitnami/kafka/bin/../libs/lz4-java-1.6.0.jar:/opt/bitnami/kafka/bin/../libs/maven-artifact-3.6.1.jar:/opt/bitnami/kafka/bin/../libs/metrics-core-2.2.0.jar:/opt/bitnami/kafka/bin/../libs/osgi-resource-locator-1.0.1.jar:/opt/bitnami/kafka/bin/../libs/paranamer-2.8.jar:/opt/bitnami/kafka/bin/../libs/plexus-utils-3.2.0.jar:/opt/bitnami/kafka/bin/../libs/reflections-0.9.11.jar:/opt/bitnami/kafka/bin/../libs/rocksdbjni-5.18.3.jar:/opt/bitnami/kafka/bin/../libs/scala-library-2.11.12.jar:/opt/bitnami/kafka/bin/../libs/scala-logging_2.11-3.9.0.jar:/opt/bitnami/kafka/bin/../libs/scala-reflect-2.11.12.jar:/opt/bitnami/kafka/bin/../libs/slf4j-api-1.7.26.jar:/opt/bitnami/kafka/bin/../libs/slf4j-log4j12-1.7.26.jar:/opt/bitnami/kafka/bin/../libs/snappy-java-1.1.7.3.jar:/opt/bitnami/kafka/bin/../libs/spotbugs-annotations-3.1.9.jar:/opt/bitnami/kafka/bin/../libs/validation-api-2.0.1.Final.jar:/opt/bitnami/kafka/bin/../libs/zkclient-0.11.jar:/opt/bitnami/kafka/bin/../libs/zookeeper-3.4.14.jar:/opt/bitnami/kafka/bin/../libs/zstd-jni-1.4.0-1.jar (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,935] INFO Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,935] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,936] INFO Client environment:java.compiler= (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,936] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,936] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,936] INFO Client environment:os.version=3.10.0-862.25.3.el7.x86_64 (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,936] INFO Client environment:user.name=? (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,936] INFO Client environment:user.home=? (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,936] INFO Client environment:user.dir=/ (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,937] INFO Initiating client connection, connectString=zookeeper-route-myproject.domain.net:80 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@4562e04d (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:25,948] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
  | [2019-08-26 10:36:31,607] INFO Opening socket connection to server zookeeper-route-myproject.domain.net:80/169.171.176.164:80. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
  | [2019-08-26 10:36:31,613] INFO Socket connection established to zookeeper-route-myproject.domain.net:80/169.171.176.164:80, initiating session (org.apache.zookeeper.ClientCnxn)
  | [2019-08-26 10:36:31,620] WARN Session 0x0 for server zookeeper-route-myproject.domain.net:80/169.171.176.164:80, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
  | java.io.IOException: Packet len1213486160 is out of range!
  | at org.apache.zookeeper.ClientCnxnSocket.readLength(ClientCnxnSocket.java:113)
  | at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:79)
  | at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
  | at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
  | [2019-08-26 10:36:31,950] INFO [ZooKeeperClient Kafka server] Closing. (kafka.zookeeper.ZooKeeperClient)
  | [2019-08-26 10:36:32,204] INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper)
  | [2019-08-26 10:36:32,204] INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn)
  | [2019-08-26 10:36:32,206] INFO [ZooKeeperClient Kafka server] Closed. (kafka.zookeeper.ZooKeeperClient)
  | [2019-08-26 10:36:32,208] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
  | kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
  | at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply$mcV$sp(ZooKeeperClient.scala:258)
  | at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:254)
  | at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:254)
  | at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
  | at kafka.zookeeper.ZooKeeperClient.kafka$zookeeper$ZooKeeperClient$$waitUntilConnected(ZooKeeperClient.scala:254)
  | at kafka.zookeeper.ZooKeeperClient.(ZooKeeperClient.scala:112)
  | at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1825)
  | at kafka.server.KafkaServer.kafka$server$KafkaServer$$createZkClient$1(KafkaServer.scala:363)
  | at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:387)
  | at kafka.server.KafkaServer.startup(KafkaServer.scala:207)
  | at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
  | at kafka.Kafka$.main(Kafka.scala:84)
  | at kafka.Kafka.main(Kafka.scala)
  | [2019-08-26 10:36:32,209] INFO shutting down (kafka.server.KafkaServer)
  | [2019-08-26 10:36:32,213] INFO shut down completed (kafka.server.KafkaServer)
  | [2019-08-26 10:36:32,213] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
  | [2019-08-26 10:36:32,215] INFO shutting down (kafka.server.KafkaServer)

**Comment by miguelaeh** [comment]
Hi @diman82 ,
Please refer to [this](https://github.com/ksprojects/zkcopy/issues/12) other issue, you can try with the options commented using the `JVMFLAGS` env var in this container.

**Comment by miguelaeh** [comment]
Hi @diman82 ,
I am not sure about if this could be related to the Openshift Route, it only match an external ip with a service but even if there are not an external IP it should work.
Did you try to set `JVMFLAGS="-Djute.maxbuffer=536870912"` ?

**Comment by bugcatcher-ops** [comment]
I am getting the same error of "Packet len* is out of range" issue, In the Bitnami helm chart I added `JVMFLAGS="-Djute.maxbuffer=536870912" ` but still getting the same error as mentioned above on Kafka side, I added the KAFKA_CFG_MAX_REQUEST_SIZE in Kafka helm chart and set the value to 10MB but no luck. can someone provide insight into this issue?

**Comment by alemorcuq** [comment]
When are you getting the error? Have you double checked the flag is set?
