### ISSUE TITLE
EACCES: permission denied using minikube restart 

### ISSUE THREAD

**Issue by revoorunischal** [bitnami/bitnami-docker-zookeeper#16]
Hi,
    I have installed kafka in aws t3a medium server using minikube,kubernates and helm chart, Its up properly and accessible. But when i bring down the AWS instance and bring it up and start the minikube the pods kafka and zookeeper are not starting and having the following errors

Zookeeper 

>  Welcome to the Bitnami zookeeper container
> Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-zookeeper
> Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-zookeeper/issues
> 
> WARN  ==> You set the environment variable ALLOW_ANONYMOUS_LOGIN=yes. For safety reasons, do not use this flag in a production environment.
> nami    INFO  Initializing zookeeper
> zookeep INFO  ==> No injected configuration files found. Creating default config file...
> zookeep INFO  ==> Setting '-Xmx1024m -Xms1024mm' as heap size...
> zookeep INFO  ==> Deploying ZooKeeper from scratch...
> zookeep INFO  ==> Validating inputs...
> Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/zookeeper/data'
> 

Kafka 

>  11:03:42.29 
>  11:03:42.29 Welcome to the Bitnami kafka container
>  11:03:42.29 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kafka
>  11:03:42.29 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kafka/issues
>  11:03:42.29 Send us your feedback at containers@bitnami.com
>  11:03:42.29 
>  11:03:42.29 INFO  ==> ** Starting Kafka setup **
>  11:03:42.34 WARN  ==> You set the environment variable ALLOW_PLAINTEXT_LISTENER=yes. For safety reasons, do not use this flag in a production environment.
> mkdir: cannot create directory '/bitnami/kafka/data': Permission denied
> 

The following is the command used to install kafka

> helm install bitnami/kafka

Can you please help me what should be changed?

**Comment by andresbono** [comment]
Hi @revoorunischal, we will need more information in order to investigate the issue.

- Can you list the PVC that you have created?
- Are you using EBS volumes in the instance?
- It is not clear to me the process of restart that you are following. Can you give us more details?
  - Do you keep the charts running and then you stop minikube and poweroff the machine?
- Are you able to launch a totally new chart deployment after rebooting the machine?
- Does it only happen for kafka chart? Are you using others?

**Comment by revoorunischal** [comment]
Hi ,

    1. I have not created any PVC of my own
    2. yes I am using EBS volumes of the aws instance
    3. So when the minikube is up and running if I stop the instance (nothing but system shutdown) and start back the instance, I will just have to start the minikube and minikube holds the instance data and brings up all the services. During this time kafka pods fail with a permission error.
    4. if i delete this helm chart application and start a new helm chart application then its working fine.
    5. Kafka is the only helm application I am using. The rest of the pods are normal kubernate application.


On the analysis of my setup after reading the pvc data provided previously. Its creating few folders in /tmp directory which is getting deleted when the system restarts and when it restarts it recreates few of them and this time it fails to create /bitnami/kafka/data.

**Comment by juan131** [comment]
Hi @revoorunischal 

Could you try installing the Helm chart with the options shown below?

```console
$ helm install bitnami/kafka \
  --name my-release \
  --set volumePermissions.enabled=true \
  --set zookeeper.volumePermissions.enabled=true
```

Does the problem persist?
