### ISSUE TITLE
Allow to set autopurge.purgeInterval / autopurge.snapRetainCount via environment variables

### ISSUE THREAD

**Issue by tkaymak** [bitnami/bitnami-docker-zookeeper#17]
Currently it is not possible to set `autopurge.snapRetainCount`, or `autopurge.purgeInterval` via environment variables, which is possible in the "official" Zookeeper image https://github.com/31z4/zookeeper-docker/blob/master/3.4.14/docker-entrypoint.sh#L23

**Comment by andresbono** [comment]
Hi @tkaymak. Would you like to implement the required changes by yourself?

**Comment by andresbono** [comment]
If you can't send a PR, we will implement the feature in any case as it seems interesting for users. Let us know what you think!

**Comment by tkaymak** [comment]
I will schedule some time this/next week to get the PR ready for you

**Comment by andresbono** [comment]
It would be greatly appreciated!!

**Comment by tkaymak** [comment]
closed by #19
