### ISSUE TITLE
TLS/Security

### ISSUE THREAD

**Issue by rahmnathan** [bitnami/bitnami-docker-zookeeper#20]
I'm trying to setup a production-like deployment of Kafka and Zookeeper using the bitnami images. In the Kafka image, instructions on how to enabled authentication + TLS are laid very well (thank you!). However, in this image/documentation I'm only seeing authentication details. I'm not very familiar with SASL, but I assume that it would be wise to enable TLS with Zookeeper in production. 

Does this image have environment variables/some way to enable TLS? Or is my assumption incorrect, and SASL is enough to fulfill production security needs? Thanks!

**Comment by tompizmor** [comment]
Hi @rahmnathan,

Thanks for using Bitnami containers. I am afraid that currently, the Zookeeper container does not support configuring TLS with environment variables. 

Regarding if only SASL authentication is enough to fulfill production security needs, it depends on your infrastructure. If your containers are not accessible from the internet, it should be fine.

Take into account that enabling SSL can introduce some penalty in the performance.

**Comment by rahmnathan** [comment]
Thanks for the quick reply @tompizmor. 

Unfortunately it's going to be a strict requirement for my team to have TLS. We deal almost entirely in PII, so any data traveling over a network (even private) must be encrypted. 

Is there any intention of adding TLS support to this image? If it's on the way, I can wait a few weeks as we're just proving this out in a Sandbox environment for now. If not, I'll have to figure something else out.

**Comment by tompizmor** [comment]
Hi @rahmnathan,

Thanks for the suggestion. I will open a task so the team can evaluate whether we can add SSL or not. However, I am afraid that we cannot provide you with any ETA about when it will be added.

**Comment by rahmnathan** [comment]
@tompizmor No problem. Thanks for considering it!

**Comment by fsniper** [comment]
TLS support is added with my latest prs. Please refer to the README file. This does not include SASL.

**Comment by marcosbc** [comment]
Thanks for updating the case! I'm proceeding to remove the on-hold label and close this ticket.
