### ISSUE TITLE
Docker zookeeper container won't start

### ISSUE THREAD

**Issue by javi9400** [bitnami/bitnami-docker-zookeeper#22]
```
/entrypoint.sh: line 27: exec: -e: invalid option
```
**Description**

Hello, i found myself having trouble starting the zookeeper container. This is what i get whenever I download the latest image.

**Steps to reproduce the issue:**

1. Downloaded the latest image of zookeeper
2. I ran this command:
```
docker run --name zookeeper bitnami/zookeeper:latest -e ALLOW_ANONYMOUS_LOGIN=yes
```

**Version**

- Output of `docker version`:

(Docker version 19.03.5, build 633a0ea)
```
zookeeper 16:26:31.32 
zookeeper 16:26:31.33 Welcome to the Bitnami zookeeper container
zookeeper 16:26:31.33 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-zookeeper
zookeeper 16:26:31.33 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-zookeeper/issues
zookeeper 16:26:31.33 Send us your feedback at containers@bitnami.com
zookeeper 16:26:31.34 

/entrypoint.sh: line 27: exec: -e: invalid option
```

**Comment by andresbono** [comment]
Hi @javi9400, you need to specify the `-e` flag and its value before the name of the container image because it's a Docker flag, not a zookeeper flag:

```
docker run --name zookeeper -e ALLOW_ANONYMOUS_LOGIN=yes bitnami/zookeeper:latest
```

Does it work for you this way?

**Comment by javi9400** [comment]
Thanks, that was the problem!! 

> Hi @javi9400, you need to specify the `-e` flag and its value before the name of the container image because it's a Docker flag, not a zookeeper flag:
> 
> ```
> docker run --name zookeeper -e ALLOW_ANONYMOUS_LOGIN=yes bitnami/zookeeper:latest
> ```
> 
> Does it work for you this way?

Thanks it works now

**Comment by andresbono** [comment]
Great to hear that, @javi9400! 🎉
