### ISSUE TITLE
Making Zookeeper ISTIO friendly

### ISSUE THREAD

**Issue by Hmr-ramzi** [bitnami/bitnami-docker-zookeeper#23]
**Description**
Unable to make zookeeper running within an ISTIO Service mesh due to the the restriction of quorumListenOnAllIPs parameter in zookeeper config to be false by default without an ability to set it on to true through an environment variable

**Steps to reproduce the issue:**

Install the helm chart of bitnami zookeeper with istio injected (which already pulls this image) and try having a zookeeper cluster of more than one node

**Describe the results you received:**

Making the docker image istio friendly by allowing zookeeper configuration quorumListenOnAllIPs as an environment variable.
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by thebwt** [comment]
This does a bit more than make ISTIO work, this also enables attaching external services and such to the pods for zookeeper.

**Comment by Hmr-ramzi** [comment]
@thebwt Thanks for your reply. What do you propose to work around on this otherwise? Is it possible to just add the option as an environment variable to zookeeper ?

**Comment by thebwt** [comment]
Ultimately it's all in /rootfs/libzookeeper.sh . The correct fix would be to add an env variable for it that defaults to false, and implementing the append logic.

Lines to change are around
https://github.com/bitnami/bitnami-docker-zookeeper/blob/master/3/debian-10/rootfs/libzookeeper.sh#L47 
and
https://github.com/bitnami/bitnami-docker-zookeeper/blob/master/3/debian-10/rootfs/libzookeeper.sh#L186

I messed around with it this morning to no avail (not the best at bash scripting).

**Comment by andresbono** [comment]
@Hmr-ramzi, @thebwt, thanks for contributing to the container with this feature! We will give some testing to the PR and we will get back to you.

**Comment by andresbono** [comment]
#24 was merged. Expect the next release of the container to include your changes!
