### ISSUE TITLE
Prometheus integration

### ISSUE THREAD

**Issue by vDMG** [bitnami/bitnami-docker-zookeeper#28]
**Description**

Hello, since 3.6.0 Zookeeper release we have a Prometheus integration [https://github.com/stickyhipp/zookeeper/commit/0c349d160fde50d4960b092f9a18c5cf6050c8f9](https://github.com/stickyhipp/zookeeper/commit/0c349d160fde50d4960b092f9a18c5cf6050c8f9).

It could be nice to add a new environement configuration variable to enable or disable the prometheus integration and make it available on https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/ and clean the exporter part no more necessary. What do you think ?

**Comment by juan131** [comment]
Hi @vDMG 

Please correct me if I'm not wrong, but these new features included at `3.6.0` allows Zookeeper to expose the Prometheus Metrics in the same container (using a different port/path). Am I right?

Our current solution for Prometheus metrics used on the [Zookeeper Chart](https://github.com/bitnami/charts/blob/master/bitnami/zookeeper) is based on using a separate deployment which uses a [Zookeeper Exporter image](https://github.com/bitnami/bitnami-docker-zookeeper-exporter) to gather metrics from Zookeeper and expose them to be consumed by Prometheus. See:

- https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/values.yaml#L266
- https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/templates/metrics-deployment.yaml

I can see some pros/cons on using you solution in favor of the other:

- PROS
  - Keep it simple: no extra deployments, containers are needed
  - Use Zookeeper "native" feature, avoid depending on 3rd party tools
- CONS
  - Multi-process?? Does the "native" solution implies running multiple processes on the container? I mean, one for Zookeeper and another one for metrics. It's a good practice to run one process per container.
  - Performance: could exposing metrics through Zookeeper affect its performance?

Please also take a look at this @javsalgar

**Comment by javsalgar** [comment]
Hi,

I've seen other applications that include an exporter in their code (I think external-dns was one of them). I didn't see the code in detail but it seems to me that it will be a thread rather than a new process. In terms of the overall performance, it may be even better because it wouldn't have a process constantly querying zk to get the metrics.

My vote would be to use the embedded solution in Zookeeper's code instead of the exporter.

**Comment by vDMG** [comment]
Hi @juan131 

Yes exactly, Zookeeper will expose himself his metrics.
It will be simpler for you to maintain the chart.

**Comment by juan131** [comment]
Hi @vDMG 

I see. I'm going to open an internal task to:

- Deprecate [Zookeeper Exporter image](https://github.com/bitnami/bitnami-docker-zookeeper-exporter)
- Adapt [Zookeeper container](https://github.com/bitnami/bitnami-docker-zookeeper) to provide a way to configure Prometheus metrics exporters.
- Adapt [Zookeeper chart](https://github.com/bitnami/charts/blob/master/bitnami/zookeeper) to user Zookeeper "native" exporters.

We'll keep you updated about our progress

**Comment by vDMG** [comment]
Cool
Thanks a lot @juan131

**Comment by andresbono** [comment]
Hi @vDMG we have just merged the PR with the changes so ZooKeeper container itself is exporting the Prometheus metrics.

Could you give it a try to the latest version of the chart and let us know if it works for you? Thanks!
