### ISSUE TITLE
Please add netcat to the image and support ZK 4 letter commands

### ISSUE THREAD

**Issue by idrennanvmware** [bitnami/bitnami-docker-zookeeper#33]
Zookeeper recommends using their 4 letter words for various healthcheck and other operations (see:  https://zookeeper.apache.org/doc/r3.4.8/zookeeperAdmin.html#sc_zkCommands )

Is it possible to have netcat installed as part of the build so that these commands can be run from inside the container?

**Comment by carrodher** [comment]
Hi, thanks for reporting this issue, you are right. We already have the `ZOO_4LW_COMMANDS_WHITELIST` environment variable implemented in the container, but without netcat is not fully functional.

I just created an internal task to add the netcat package (or `nc` depending on the distro) to our images. I will update this issue once the image is released.

Also, please note that the `ZOO_4LW_COMMANDS_WHITELIST` is set to `srvr, mntr` by default, if you want to enable more commands you need to provide more items to this list or `*` to enable all of them.

**Comment by idrennanvmware** [comment]
Thanks @carrodher  - appreciate the quick response.   Right now we are wrapping this in our own package but that's obviously not ideal.  Is there a "rough" timeline we can expect?  I ask because I'm trying to determine if we should shelve our wrapper now vs continuing to implement the builds, etc

**Comment by carrodher** [comment]
Hi, it was tested & released through our pipeline some minutes ago (this is the commit https://github.com/bitnami/bitnami-docker-zookeeper/commit/baece1e26ec27a6fe8d31e67ccefb7c95d2daaeb).
You can also find those changes already present in the different rolling tags: `3-debian-10`, `3.6.1-debian-10-r36`, `3`, `3.6.1`, `latest`.

An example using `latest`:
```
I have no name!@b79ca989bbc3:/$ echo srvr | nc localhost 2181
Zookeeper version: 3.6.1--104dcb3e3fb464b30c5186d229e00af9f332524b, built on 04/21/2020 15:01 GMT
Latency min/avg/max: 0/0.0/0
Received: 3
Sent: 3
Connections: 1
Outstanding: 0
Zxid: 0x0
Mode: standalone
Node count: 5
```

**Comment by idrennanvmware** [comment]
Works great - thanks @carrodher .   I believe we can close this now :)

**Comment by carrodher** [comment]
Nice, thanks for confirming! 🎉
