### ISSUE TITLE
Java checksum did not match and apt-utils is not installed

### ISSUE THREAD

**Issue by LeukocytesTT** [bitnami/bitnami-docker-zookeeper#43]
Hello! I am trying to build zookeeper myself from Dockerfile of this repository. 
But when i did that, It throwed an some errors; Please help me with this problem! Thank you! 
I use docker version 19.03.13, build 4484c46d9d
and docker-compose version 1.22.0, build f46880fe

1. First, an error when installing some dependency packages.
```
Get:25 http://deb.debian.org/debian buster/main amd64 netcat all 1.10-41.1 [9034 B] 
debconf: delaying package configuration, since apt-utils is not installed
Fetched 5322 kB in 1min 8s (78.1 kB/s)
Selecting previously unselected package libncurses6:amd64.
```
2. Second, an error when installing java version 11 with checksum checking. 

```Downloading java-11.0.9-0-linux-amd64-debian-10 package
Verifying package integrity
java-11.0.9-0-linux-amd64-debian-10.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Removing intermediate container 8ecb587f5cdc```

**Comment by miguelaeh** [comment]
Hi @LeukocytesTT ,
Could you share the exact steps you are following and the commands you are executing?

**Comment by LeukocytesTT** [comment]
I used this command to build this repo! 
```
sudo docker build -t bitnami/zookeeper:latest 'https://github.com/bitnami/bitnami-docker-zookeeper.git#master:3/debian-10'
```
When I cloned this repo and build from Dockerfile, it also threw these errors

**Comment by miguelaeh** [comment]
Hi @LeukocytesTT ,
I am not able to reproduce the issue, I can build the image in both ways.

Anyway, try manually removing the checksum from the Dockerfile if this error continues for you
