### ISSUE TITLE
Bitnami image ignores ZOO_ADMINSERVER_ENABLED: 'false'

### ISSUE THREAD

**Issue by fksimon** [bitnami/bitnami-docker-zookeeper#50]
**Description**

The default zookeeper image allows you to disable the zookeeper admin server by setting the ZOO_ADMINSERVER_ENABLED environment variable to false.   By default it is enabled.

using the bitnami image it ignores the flag and always starts the admin server.

**Steps to reproduce the issue:**

1. docker-compose up -d
2. docker-compose exec zookeeper bash
3. curl http://localhost:8080/commands

With flag set to false the admin server should not start

**Describe the results you received:**

admin server is running 

**Describe the results you expected:**

admin server should not be running, curl should have returned a 404

**Additional information you deem important (e.g. issue happens only occasionally):**

Works properly in zookeeper provided image

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 457
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: TNPC:FM6Q:OVYU:NU45:H3J6:FNJE:RLFS:GPJY:ONHE:CRS2:S7FD:QL6P
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 49
  Goroutines: 53
  System Time: 2021-02-22T19:20:44.827057325Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

Compose file

```
version: '2.4'

services:
  zookeeper:
    image: bitnami/zookeeper:3.6.1
    #image: zookeeper:3.6.1
    ports:
      - 2181
    healthcheck:
      test: echo ruok | nc localhost 2181 | grep imok
      interval: 15s
    environment:
      JVMFLAGS: -Dzookeeper.4lw.commands.whitelist=ruok
      ZOO_ADMINSERVER_ENABLED: 'false'
      ALLOW_ANONYMOUS_LOGIN: 'yes'
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker desktop for mac and same issue in Kubernetes using bitnami zookeeper helm chart

**Comment by fksimon** [comment]
Workaround is to use JVMFLAGS: -Dzookeeper.4lw.commands.whitelist=ruok -Dzookeeper.admin.enableServer=false, but not consistent between images.

**Comment by juan131** [comment]
Hi @fksimon 

You're totally right! Thanks so much for this great suggestion. I'll open a task to implement the missing environment variable so it's easier to enable/disable the admin server.

I'll keep you updated about our progress.

**Comment by pawelrubin** [comment]
What is the status of this issue?

**Comment by pawelrubin** [comment]
The admin server can alternatively be disabled via a JVM flag
```yaml
      ...
      environment:
        JVMFLAGS: -Dzookeeper.admin.enableServer=false
```

source: https://zookeeper.apache.org/doc/r3.5.7/zookeeperAdmin.html#sc_adminserver_config

**Comment by juan131** [comment]
Thanks so much for sharing that solution!! I'll share it in the associated task

**Comment by smatvienko-tb** [comment]
Hey, @fksimon! Looks like the issue has been resolved in the latest master with variable 
`ZOO_ENABLE_ADMIN_SERVER=no`

**Comment by juan131** [comment]
Correct! This was solved at https://github.com/bitnami/bitnami-docker-zookeeper/pull/69
