### ISSUE TITLE
Please provide ZooKeeper 3.4.11 stack+image

### ISSUE THREAD

**Issue by copart-jafloyd** [bitnami/bitnami-docker-zookeeper#51]
**Description**

I need to run some tests with zookeeper 3.4.11 in kubernetes (installed via helm chart), but the oldest docker image has zookeeper 3.4.12, so there isn't a stack for 3.4.11 available to download.

Could you please build a stack for zookeeper 3.4.11 that I can use with k8s? Or can you point me to some docs on how to build it myself?

**Steps to reproduce the issue:**

1. Prepare a values.yaml file to adjust the zookeeper image used by the helm chart: https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/values.yaml#L17
2. Look for a 3.4.11 on [dockerhub](https://hub.docker.com/r/bitnami/zookeeper/tags/?page=1&ordering=last_updated&name=3.4.11)
3. Try to build a custom the docker image to use 3.4.11 instead of 3.6.2 (requires editing this line: https://github.com/bitnami/bitnami-docker-zookeeper/blob/master/3/debian-10/Dockerfile#L14)

**Describe the results you received:**

There is no bitnami stack for zookeeper 3.4.11, so I can't build a docker image with it.

**Describe the results you expected:**

Either find a docker image or the stack needed to build one.

**Additional information :**

_I originally posted this [on the forum](https://community.bitnami.com/t/old-version-of-zookeeper-stack/92597)._

**Version**

- Output of `docker version`:

```
Client:
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.15.6
 Git commit:        03fa4b8
 Built:             Sat Dec 12 20:00:39 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 86
  Running: 78
  Paused: 0
  Stopped: 8
 Images: 57
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 3.846GiB
 Name: docker-desktop
 ID: MXNJ:KHBG:BLK6:USPY:I64P:JMPE:UA3P:7V74:VZJM:5JVX:ULRP:3KDO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I'm using Docker for MAC + kubernetes (k8s provided by Docker for MAC) for the moment. Once I get things installed I'll transfer over to a larger multi-node k8s cluster to finish running my tests.

**Comment by alemorcuq** [comment]
As you said, we have no docker image for Apache Zookeeper 3.4.11.

The `libcomponent.sh` script just extracts the Zookeeper files into the right directories, so you can try placing the Zookeeper 3.4.11 files in `/opt/bitnami/zookeeper` and see if that works. Keep in mind that version is quite old, so I can't guarantee it is going to work.
