### ISSUE TITLE
Zookeeper.log file not created, rather log outputs are being piped to console.

### ISSUE THREAD

**Issue by nullpointer77** [bitnami/bitnami-docker-zookeeper#53]
log4j configuration doesn't appear to be writing zookeeper log files to the log directory.  I do not see any way of changing this with environment variables.  I only see log files via attaching directly to the running container which makes me think it's just piping log data to the console.

1. Launch the latest version of the zookeeper container
2. docker exec -it [whatever] /bin/bash
3. Navigate to /opt/bitnami/zookeeper/logs
4. Notice that no logs exist

**Describe the results you received:**

No log files exist from what I can tell.  I can only monitor logs via docker attach [whatever].  I also don't have a way to export log files from the container for trouble shooting as they don't seem to exist.

**Describe the results you expected:**

I would expect to either see zookeeper logs in the logs directory or have an environment variable to define the log directory.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1038-aws
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.698GiB
 Name: ip-172-31-24-248
 ID: M4P6:7AGT:D3XH:2FKK:MAIB:ZQZY:MQMY:O7SQ:YGC2:UPIL:X43Q:GAFH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

Running in AWS ubuntu linux 20.04 focal

**Comment by rafariossaa** [comment]
Hi,
  Would `docker logs <name_of_the_contaier>` would work in you case ?

**Comment by nullpointer77** [comment]
This work around will work for me.

**Comment by nullpointer77** [comment]
I still think that this should be addressed at some point.  `docker logs` certainly works for me but it's returning a 200+MB log file to the linux host I'm working on.  It seems like the log4j configuration is just being ignored as it's not writing logs in the container nor rolling??  However, I could be wrong here.

**Comment by rafariossaa** [comment]
Hi,
  You can check the log4 configuration in the file: `/opt/bitnami/zookeeper/conf/log4j.properties`. It is using `zookeeper.root.logger=INFO, CONSOLE`. Hence the log is written to the console.

**Comment by nullpointer77** [comment]
Let's go ahead and close this as the problem here lies between the screen and the chair.  Thanks for the help with this.
