### ISSUE TITLE
Is there any possible that publish a newer version for Zookeeper-exporter?

### ISSUE THREAD

**Issue by max-tian** [bitnami/bitnami-docker-zookeeper#56]
I checked the information from docker hub. It says the newest version is one year ago. Is there a plan for publishing a newer version for zk exporter?

**Comment by migruiz4** [comment]
Hi @max-tian,

I'm sorry but we no longer maintain the `zookeeper-exporter` image as, since version 3.6.0, Zookeeper can export metrics to Prometheus natively: https://zookeeper.apache.org/doc/current/zookeeperMonitor.html
