### ISSUE TITLE
Add leaderServes configurable via environment variables

### ISSUE THREAD

**Issue by blafry** [bitnami/bitnami-docker-zookeeper#66]
I want to ask if it would be possible to extend the ZooKeeper configuration via environment variables by leaderServes parameter?

_leaderServes : (Java system property: zookeeper.leaderServes) Leader accepts client connections. Default value is "yes". The leader machine coordinates updates. For higher update throughput at the slight expense of read throughput the leader can be configured to not accept clients and focus on coordination. The default to this option is yes, which means that a leader will accept client connections._

https://zookeeper.apache.org/doc/r3.7.0/zookeeperAdmin.html

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. I believe this should be set in this line of libzookeeper.sh https://github.com/bitnami/bitnami-docker-zookeeper/blob/master/3.7/debian-10/rootfs/opt/bitnami/scripts/libzookeeper.sh#L160

We are open to contributions, would you like to submit a PR with the change? You only need to modify one of the branch folders.
