### ISSUE TITLE
Running the container fails with 'exec /opt/bitnami/scripts/zookeeper/entrypoint.sh: exec format error'

### ISSUE THREAD

**Issue by igwejk** [bitnami/bitnami-docker-zookeeper#73]
### Name and Version

bitnami/zookeeper:latest

### What steps will reproduce the bug?

1. On MacOS (Apple M1)
2. With `lima` client
3. Run
   ```bash
   lima nerdctl run --rm --name zookeeper-server -e ALLOW_ANONYMOUS_LOGIN=yes bitnami/zookeeper:latest
   ```

### What is the expected behavior?

`zookeeper` process should start running

### What do you see instead?

The below error is printed
```
exec /opt/bitnami/scripts/zookeeper/entrypoint.sh: exec format error
```

### Additional information

Please note that I use [`lima`](https://github.com/lima-vm/lima) for executing the container.

**Comment by javsalgar** [comment]
Hi,

I'm afraid we currently don't have support for ARM architecture in our containers. It's something that we have in our backlog, but there are no immediate plans to work on it.

As soon as there are news, we will let you know.
