### ISSUE TITLE
Prometheus Variables not working

### ISSUE THREAD

**Issue by dalejandroso** [bitnami/bitnami-docker-zookeeper#74]
### Name and Version

bitnami/zookeeper:3.5.9

### What steps will reproduce the bug?

1. Set the next varibles

ZOO_ENABLE_PROMETHEUS_METRICS: yes
ZOO_PROMETHEUS_METRICS_PORT_NUMBER: 7000

The settings will be set to zoo.cfg but the service won't start Prometheus

### What is the expected behavior?

The starting log won't show the Prometheus start

### What do you see instead?

With latest version the configuration works fine

**Comment by juan131** [comment]
Hi @dalejandroso 

So you can reproduce this issue with version `3.5.9` but it's working with version `3.7.0`. Am I right?
Could you please share the complete DockerCompose (or equivalent CLI command) you're using to deploy the container?

**Comment by dalejandroso** [comment]
Hi @juan131

A little more context. I'm using Kafka 2.8.x (bitnami/kafka:2.8.1) and following the interoperability matrix the zookeeper version is 3.5.9. 

https://docs.confluent.io/platform/current/installation/versions-interoperability.html

You can reproduce the issue using the bitnami zookeeper image < 3.6.

I've attached a simple docker compose, just look the test container logs.

Regards,
[docker-compose.txt](https://github.com/bitnami/bitnami-docker-zookeeper/files/8097958/docker-compose.txt)

**Comment by migruiz4** [comment]
Hi @dalejandroso,

I'm sorry but the Zookeeper metricsProvider was introduced in Zookeeper 3.6: https://zookeeper.apache.org/doc/r3.7.0/zookeeperMonitor.html

In versions 3.5 and prior, it was necessary to use [an exporter](https://hub.docker.com/r/bitnami/zookeeper-exporter) to extract metrics, but the image `bitnami/zookeeper-exporter` is no longer maintained, so I would recommend moving to a higher version when possible.
