### ISSUE TITLE
TLS quorum host name verification issue with docker-compose

### ISSUE THREAD

**Issue by rbuffat** [bitnami/bitnami-docker-zookeeper#76]
### Name and Version

bitnami/zookeeper:3.7

### What steps will reproduce the bug?

I'm in the process of creating a docker-compose setup of Kafka with zookeeper using TLS for all communications to gain experience using it. Unfortunately, it seems to be tricky to set up TLS for the zookeeper quorum. 

**First Attempt**

When using the service name (e.g. `zookeeper`, `zookeeper2`, .. ) of the container as `common name` for the certificate, I get the following error messages:

```
kafka_ssl-zookeeper-1  |   Caused by: java.security.cert.CertificateException: Failed to verify both host address and host name
kafka_ssl-zookeeper-1  |   Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <kafka_ssl-zookeeper2-1.kafka_ssl_default> doesn't match common name of the certificate subject: zookeeper2
```

_To reproduce:_ 

A working example can be found here: https://github.com/rbuffat/kafka_playground/tree/main/kafka_ssl
The keys/certificates were generated using https://github.com/rbuffat/kafka_playground/blob/main/kafka_ssl/create_ssl_certificates.py

Zookeeper is started using `docker-compose up zookeeper zookeeper2 zookeeper3`

**Second Attempt**

When using the hostname that is identified by zookeeper (`kafka_ssl_v2-zookeeper-1.kafka_ssl_default`) as common name as well as the "ZOO_SERVERS: kafka_ssl_v2-zookeeper-1.kafka_ssl_default:2888:3888,kafka_ssl_v2-zookeeper2-1.kafka_ssl_default:2888:3888,kafka_ssl_v2-zookeeper3-1.kafka_ssl_default:2888:3888" configuration options for the zookeeper image, the following error occurs:

```
kafka_ssl_v2-zookeeper-1  | 2022-03-28 13:42:02,235 [myid:1] - ERROR [ListenerHandler-kafka_ssl_v2-zookeeper-1.kafka_ssl_default:3888:QuorumCnxManager$Listener$ListenerHandler@1094] - Exception while listening
kafka_ssl_v2-zookeeper-1  | java.net.SocketException: Unresolved address
```

_To reproduce:_ 

A working example can be found here: https://github.com/rbuffat/kafka_playground/tree/main/kafka_ssl_v2
The keys/certificates were generated using https://github.com/rbuffat/kafka_playground/blob/main/kafka_ssl_v2/create_ssl_certificates.py

Zookeeper is started using `docker-compose up zookeeper zookeeper2 zookeeper3`

**Third Attempt**

When using the hostname that is identified by zookeeper (`kafka_ssl_v2-zookeeper-1.kafka_ssl_default`) as common name as well as the "ZOO_SERVERS: zookeeper:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888" configuration options for the zookeeper image, I get the following error:

```
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <zookeeper2> doesn't match common name of the certificate subject: kafka_ssl_v2-zookeeper2-1.kafka_ssl_default
```

_To reproduce:_ 

The example from the second attempt can be used, but `ZOO_SERVERS` needs to be changed in docker-compose.yml  : https://github.com/rbuffat/kafka_playground/tree/main/kafka_ssl_v2
The keys/certificates were generated using https://github.com/rbuffat/kafka_playground/blob/main/kafka_ssl_v2/create_ssl_certificates.py

To summarize, it looks as the problem seems to be related to how docker resolves hostnames. I assume one way to solve this issue would be to disable hostname verification for the quorum. However, there seems to be no "KAFKA_CFG_" analog to set arbitrary config parameters for this zookeeper image. I'm currently not sure what the best way would be to set the following configuration option: 

> ssl.hostnameVerification and ssl.quorum.hostnameVerification : (Java system properties: zookeeper.ssl.hostnameVerification and zookeeper.ssl.quorum.hostnameVerification) New in 3.5.5: Specifies whether the hostname verification is enabled in client and quorum TLS  Negotiation process. Disabling it only recommended for testing purposes. Default: true

But better would it be to configure zookeeper properly in the first place, if this is possible.

### What is the expected behavior?

Zookeeper is setup with quorum and TLS connections

### What do you see instead?

The error messages mentioned above. 

### Additional information

As I'm only starting to dive into Kafka and zookeeper, it is highly likely that this issue is just user error. My apologies in advance if this is the case.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami Zookeeper container image but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by rbuffat** [comment]
Thanks @carrodher for your reply!  Could you recommend a forum to post such issues? 

Regarding the setting of the `zookeeper.ssl.quorum.hostnameVerification`, what would be the recommended way of setting this option with this docker image?

The mechanism implemented with bitnami's kafka image seems not to be implemented with this project:
https://github.com/bitnami/bitnami-docker-kafka/blob/1a8923089e173f919ac3d3c6632dfd8852296e83/3.1/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L646-L666

Would you be interested in a PR to add this functionality? If yes I could give it a try. Although I'm not yet sure what the best way would be to map from upper case environment variables (e.g. `ZOO_CFG_SSL_QUORUM_HOSTNAMEVERIFICATION`) to the camel case config option names of Zookeeper (`zookeeper.ssl.quorum.hostnameVerification`).

**Comment by carrodher** [comment]
Thanks, yes, for this specific topic you can create a PR; the Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/bitnami-docker-zookeeper/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

Regarding general information about the application itself and how it can be configured my recommendation would be to visit the zookeeper forum at https://zookeeper.apache.org/lists.html
