### ISSUE TITLE
Security Hardening readOnlyRootFilesystem

### ISSUE THREAD

**Issue by acherla** [bitnami/bitnami-docker-zookeeper#82]
### Name and Version

bitnami/zookeeper:latest

### What steps will reproduce the bug?

Description: Bitnami's zookeeper docker image should support readOnlyRootFilesystem for hardened Kubernetes environments.  Configuring VOLUMES in the docker container for tmp & opt directories should remediate the above issue when enabling readOnlyRootFilesystem=true in kubernetes manifest files.  

### What is the expected behavior?

/tmp & /opt should be able to be written to when running with readOnlyRootFilesystem = true

### What do you see instead?

 /tmp & /opt are read only filesystems when readOnlyRootFilesystem = true, thus an exception is thrown and the container crashes

**Comment by javsalgar** [comment]
Hi! Thank you so much for the input. We evaluated implementing this in the past and we got to this conclusion:

https://github.com/bitnami/charts/issues/8500#issuecomment-1057118831

I'm afraid that we don't plan to work on this on the short-mid term.
