### ISSUE TITLE
ZOO_ENABLE_PROMETHEUS_METRICS issue

### ISSUE THREAD

**Issue by wilokecom** [bitnami/bitnami-docker-zookeeper#84]
### Name and Version

bitnami/bitnami-docker-zookeeper:3.8

### What steps will reproduce the bug?

1. set ZOO_ENABLE_PROMETHEUS_METRICS=yes under docker-compose
2. set ZOO_PROMETHEUS_METRICS_PORT_NUMBER=7070
3. Visit localhost:7070 and I got HTTP ERROR 404 Not Found

### What do you see instead?

<h2 style="color: rgb(0, 0, 0); font-family: Times; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 404 Not Found</h2>

URI: | /
-- | --
404
Not Found
org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-7d9e8ef7

<br class="Apple-interchange-newline">
![Screen Shot 2022-06-13 at 09 59 24](https://user-images.githubusercontent.com/47608417/173271754-70ffe2d8-e217-4d98-857c-8ec0bac788bf.png)

**Comment by wilokecom** [comment]
Sorry, It's my missing. It works well

**Comment by rafariossaa** [comment]
Hi,
  Don't worry.
