### ISSUE TITLE
Does zoo.cfg accept configuration other than what have been supplied?

### ISSUE THREAD

**Issue by TheXs** [bitnami/bitnami-docker-zookeeper#86]
### Name and Version

latest

### What is the problem this feature will solve?

eg: We want  to change the configuration "forceSync" to be "no", is there any way to put that into the zoo.cfg?ZOO_FORCE_SYNC is obviously unavailable now. Thanks for reply.

### What is the feature you are proposing to solve the problem?

support customized configuration

**Comment by javsalgar** [comment]
Hi,

You can mount your own zoo.cfg file in the container. Did you try that?
